### ISSUE TITLE
Harvesting any THREDDS causes NullPointerException

### ISSUE THREAD

**Issue by alxcost** [geonetwork/docker-geonetwork#78]
Hello,

I'm try to harvest standard THREDDS services but whenever I try to do so, GeoNetwork is throwing a NullPointerException with the following stacktrace:
```
java.lang.NullPointerException
        at org.fao.geonet.kernel.harvest.harvester.thredds.Harvester.processServices(Harvester.java:1481)
        at org.fao.geonet.kernel.harvest.harvester.thredds.Harvester.harvestCatalog(Harvester.java:416)
        at org.fao.geonet.kernel.harvest.harvester.thredds.Harvester.harvest(Harvester.java:284)
        at org.fao.geonet.kernel.harvest.harvester.thredds.ThreddsHarvester.doHarvest(ThreddsHarvester.java:76)
        at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester$HarvestWithIndexProcessor.process(AbstractHarvester.java:647)
        at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester.harvest(AbstractHarvester.java:718)
        at org.fao.geonet.kernel.harvest.harvester.HarvesterJob.execute(HarvesterJob.java:69)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```

The Webpage UI just shows:
```
Harvest error error
[] 
```

This seems to be happening with any THREDDS service (my own or any publicly available).
Some examples: https://www.ncdc.noaa.gov/wct/data.php, https://tds.marine.rutgers.edu/thredds/met/wrf/catalog.html

My setup is running through docker-compose using the following YML:
```
version: '3.1'
services:
  geonetwork:
    image: geonetwork:3.12.2
    restart: always
    environment:
      DATA_DIR: /var/lib/geonetwork
      GEONETWORK_DB_NAME: /var/lib/geonetwork/db/gn
    volumes:
      - ./geonetwork_data:/var/lib/geonetwork
```

Does anyone have an idea of what could be causing this? Other harvesters seem to be working fine (i.e. harvesting other GeoNetworks, OGC SOS, etc...)

**Comment by alxcost** [comment]
Hello,

This issue seems to be happening on native installations too and doesn't seem to be related to docker.
I've opened an issue on https://github.com/geonetwork/core-geonetwork/issues/6113

Sorry for the confusion.
