### ISSUE TITLE
 Query returned an error. Check the console for details.

### ISSUE THREAD

**Issue by fdq09eca** [geonetwork/docker-geonetwork#94]
I installed 4.2.1.I am not sure if it has been installed successfully. it ends up with the following message
```
Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.41/containers/aa5698b40b1b5d1ae44fef292442ff6431ea6decff782bf19634fb86b476c923/start": context canceled
```
when i fire up localhost:8080, it give me the following 
![image](https://user-images.githubusercontent.com/51902242/206551188-9162ec75-f824-4abd-ad5a-81590376f8ab.png)

I think it is a elastic search problem? 

see the following elastic search log below:

```
2022-12-08 19:45:36 "stacktrace": ["org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:601) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:332) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:636) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:415) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction.lambda$performPhaseOnShard$0(AbstractSearchAsyncAction.java:240) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction$2.doRun(AbstractSearchAsyncAction.java:308) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
2022-12-08 19:45:36 "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
2022-12-08 19:45:36 "at java.lang.Thread.run(Thread.java:832) [?:?]",
2022-12-08 19:45:36 "Caused by: org.elasticsearch.action.NoShardAvailableActionException",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:448) ~[elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:397) [elasticsearch-7.11.1.jar:7.11.1]",
2022-12-08 19:45:36 "... 9 more"] }
2022-12-08 19:45:36 {"type": "deprecation", "timestamp": "2022-12-08T19:45:36,981Z", "level": "DEPRECATION", "component": "o.e.d.i.m.RootObjectMapper", "cluster.name": "docker-cluster", "node.name": "3fc68831fa82", "message": "dynamic template [dateType] has invalid content [{\"match\":\"ft_*_d\",\"mapping\":{\"format\":\"\",\"type\":\"double\"}}], attempted to validate it with the following match_mapping_type: [object, string, long, double, boolean, date, binary], caused by [unknown parameter [format] on mapper [__dynamic__dateType] of type [double]]", "cluster.uuid": "LFqwZK0jTWeT3sZ4hLgnVA", "node.id": "4LFPR92tS--O-sE1QgGAiA"  }
2022-12-08 19:45:38 {"type": "server", "timestamp": "2022-12-08T19:45:38,564Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "3fc68831fa82", "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.dashboards_1][0]]]).", "cluster.uuid": "LFqwZK0jTWeT3sZ4hLgnVA", "node.id": "4LFPR92tS--O-sE1QgGAiA"  }
2022-12-08 19:46:30 {"type": "deprecation", "timestamp": "2022-12-08T19:46:30,196Z", "level": "DEPRECATION", "component": "o.e.d.c.m.IndexNameExpressionResolver", "cluster.name": "docker-cluster", "node.name": "3fc68831fa82", "message": "this request accesses system indices: [.apm-agent-configuration, .apm-custom-link, .kibana_task_manager_1], but in a future major version, direct access to system indices will be prevented by default", "cluster.uuid": "LFqwZK0jTWeT3sZ4hLgnVA", "node.id": "4LFPR92tS--O-sE1QgGAiA"  }
```

any solution? Thanks!

**Comment by gioman** [comment]
Fresh installation (with Docker) of 4.2.5

![image](https://github.com/geonetwork/docker-geonetwork/assets/1951107/acd47983-07fc-421b-a8e1-f53d93b21d10)

any suggestion please?

**Comment by gioman** [comment]
Error seems gone after loading samples as described here

https://geonetwork-opensource.org/manuals/3.12.x/en/install-guide/loading-samples.html
